[package]
name = "firestone"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
axum.workspace = true
clap.workspace = true
clap_complete.workspace = true
firestone-core = { path = "../firestone-core" }
futures-util.workspace = true
hyper.workspace = true
hyperlocal.workspace = true
hyper-util.workspace = true
jiff.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
signal-hook.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower.workspace = true
unicode-width.workspace = true

[dev-dependencies]
fs2.workspace = true
http-body-util.workspace = true
nix.workspace = true
sha2.workspace = true
tempfile.workspace = true
wait-timeout.workspace = true

[lints]
workspace = true
